### ISSUE TITLE
Docker image not found.

### ISSUE THREAD

**Issue by ldsnbplus** [ossrs/srs-cloud#123]
Failed to pull the image, image not found.

root@instance-20221210-1433:~# docker pull registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:1 Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/ossrs/srs-cloud:1 not found: manifest unknown: manifest unknown

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.
