### ISSUE TITLE
CLI: 部署在自己的服务器中

### ISSUE THREAD

**Issue by yanest** [ossrs/srs-cloud#24]
面板挺好用的，能不能部署在自己的环境中呢

**Comment by winlinvip** [comment]
有这个计划，支持命令行安装到Ubuntu系统。

**Comment by yanest** [comment]
前天试着自己安装了一下，完全安装不上

Winlin ***@***.***> 于 2022年4月4日周一 上午11:33写道：

**Comment by winlinvip** [comment]
已经支持了，请使用命令行安装宝塔，然后用宝塔安装云SRS。

具体用法请参考 https://github.com/ossrs/srs-cloud/issues/4#support-platform

**Comment by yanest** [comment]
老大威武，说干就干

Winlin ***@***.***> 于 2022年5月21日周六 上午8:38写道：
