### ISSUE TITLE
how to install srs-cloud on google cloud?

### ISSUE THREAD

**Issue by thanhntvt** [ossrs/srs-cloud#28]
Hi,

I'm family with GG cloud, so I want to install the srs-cloud on GG cloud instead Digital Ocean! I tried to GG search for the guideline but haven't got anything...

Appreciate someone would shares the way to setup on GG cloud...

**Comment by winlinvip** [comment]
We're developing the CLI for installing srs-cloud on any linux, so please wait for about a month, we will release that.

**Comment by winlinvip** [comment]
You could install SRS on google cloud with aaPanel, please follow [this tutorial](https://blog.ossrs.io/how-to-setup-a-video-streaming-service-by-aapanel-9748ae754c8c).
