### ISSUE TITLE
Restream：支持多流转推

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs-cloud#34]
目前云SRS支持的是单流转推，整体方案简单，操作简单。

但如果有多路流推送到SRS，只能随机选择一路流，这样可以实现热备。

不过有朋友反馈热备不那么重要。而支持多流转推更有用，目前只能开多台云SRS，管理起来麻烦。

需要仔细考虑下：

1. 有些人是单流的，所以不能增加操作复杂性。

2. 是否有热备要求，如果要搞热备，支持多流转推就非常复杂了。

3. 如果未来考虑转码啥的，想都不敢想，非常非常复杂。

如果你用到了多流转推业务，欢迎说说你的想法。

**Comment by guoronghui** [comment]
对我来说，热备和稳定性才是最重要的。

**Comment by winlinvip** [comment]
如果只是热备和稳定性，那么单流转推是最合适的，弄多流就复杂了，复杂了就不稳定。

**Comment by winlinvip** [comment]
Won't support it.
