### ISSUE TITLE
DVR: 支持本地录制，录制保留本地文件

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs-cloud#42]
在公司内网服务器跑云SRS，录制到本地磁盘，本地磁盘足够大。

云SRS本地录制，会有一些已知问题：

1. 如果流的路数特别多，磁盘会很忙，特别是挂共享存储，需要监控磁盘IO和负载。解法：使用高性能磁盘和共享存储。
2. 虽然本地磁盘足够大，但云存储是真的无限大，而本地磁盘其实还是有限的，需要监控磁盘空间。解法：扩大磁盘空间。
3. 暂时不支持本地文件的管理，比如删除和清理等。解法：可以借助宝塔等服务器管理工具。

**Comment by winlinvip** [comment]
Fixed in 4.0.244

**Comment by cshitian** [comment]
是否能支持API获取本地文件的播放地址

**Comment by winlinvip** [comment]
云SRS是全部有API的，具体请看FAQ。
