### ISSUE TITLE
宝塔面板部署时出现问题，求教

### ISSUE THREAD

**Issue by immoke** [ossrs/srs-cloud#49]
请教一下，我在用纯净的centos7_2009 下，纯净的宝塔面板7.9.8，安装srs-cloud，出现2个问题，求指导
1）部署完成后，首次打开管理页面，要求设置初始密码。
我用chrome和edge，都无法点击“设置管理员密码”

2）服务器重启后，2022端口找不到，导致docker中的srs-cloud:platform-v1.0.232启动报错。

**Comment by immoke** [comment]
补充说明宝塔面板中 srs服务无法启动，错误在/var/log/message里是：
Feb 13 11:24:43 srs-cloud kernel: swapon: swapfile has holes
Feb 13 11:24:43 srs-cloud bootstrap: swapon: /srs-swapfile：swapon 失败: 无效的参数
Feb 13 11:24:43 srs-cloud bootstrap: Turn on swap memory failed
Feb 13 11:24:43 srs-cloud bootstrap: Execute for each run script failed
Feb 13 11:24:43 srs-cloud systemd: srs-cloud.service: main process exited, code=exited, status=1/FAILURE
Feb 13 11:24:43 srs-cloud systemd: Unit srs-cloud.service entered failed state.
Feb 13 11:24:43 srs-cloud systemd: srs-cloud.service failed.

**Comment by winlinvip** [comment]
请安装最新的版本
