### ISSUE TITLE
我使用咱们的云srs 再设置云录制的时候，设置腾讯云的key，报500错误如图，不知道什么问题造成的

### ISSUE THREAD

**Issue by wuxiandashu** [ossrs/srs-cloud#51]
![8030d27422c978755b48b643732e7b0](https://user-images.githubusercontent.com/28449500/223007835-37e03336-e257-47e2-9feb-90158b569cc5.png)
![bb62b4a20cdee441a8e149e059f54c2](https://user-images.githubusercontent.com/28449500/223007842-592ddb9e-0995-4e0a-bffd-7f56c9a878ae.png)

**Comment by wuxiandashu** [comment]
问题解决了。，
需要先再腾讯云后台 开通vos权限 跟 对象存储业务之后，再来配置key

**Comment by winlinvip** [comment]
感谢反馈。
