### ISSUE TITLE
docker部署，虚拟直播的文件上传了，如何删除，同个文件虚拟直播到好几个平台，只能重复上传，不能本地选择。

### ISSUE THREAD

**Issue by edisonzf2020** [ossrs/srs-cloud#52]
ubuntu上docker部署，虚拟直播很好用，不过遇到几个问题：
1、虚拟直播上传的文件不知道怎么删除。
2、一个文件要虚拟直播到几个平台，需要重复上传，很占空间。能否除了上传还能选择服务器本地文件的方式。

**Comment by winlinvip** [comment]
可以结合虚拟直播，推送到云SRS本机，然后用多平台直播推多个平台。
