### ISSUE TITLE
无法升级HOST和切换SRS版本

### ISSUE THREAD

**Issue by MonoLogueChi** [ossrs/srs-cloud#55]
基本信息

- 腾讯云CVM部署，广东区
- 镜像为 SRS 4.6
- 当前版本 HOST v1.0.256

现象 无法升级 HOST，无法切换SRS版本，点击升级，会提示正在升级，然后一段时间提示升级成功，但实际是升级失败了。实际upgrade请求第一次是返回502，后面再尝试返回500错误，重启后无法打开网页管理端，检查2022端口，没有应用监听

**Comment by winlinvip** [comment]
腾讯云的镜像需要升级，我们正在规划这事。

可以考虑直接用宝塔部署最新的版本，或者用docker部署。

宝塔：https://ossrs.net/lts/zh-cn/faq-srs-cloud#bt-install-manually

docker: https://github.com/ossrs/srs-cloud/issues/44

**Comment by winlinvip** [comment]
Docker无法升级，升级功能将不会支持。
