### ISSUE TITLE
cpu被限流30%

### ISSUE THREAD

**Issue by nmww** [ossrs/srs-cloud#56]
宝塔安装了srs；
推流中发现，服务器cpu无法突破30%，分析远远，是推流到 srs，被cpu限流了？
请问这个cpu流量限制，在哪里更改限制数值。
![1879a65b41f64401a0995d.png](1879a65b41f64401a0995d)
![1879a653be7644019ea95c.png](1879a653be7644019ea95c)

**Comment by winlinvip** [comment]
Can't replay.
