### ISSUE TITLE
虚拟机环境下在宝塔中安装的srs，虚拟直播无法上传文件，提示错误。

### ISSUE THREAD

**Issue by garyzhao1** [ossrs/srs-cloud#58]
虚拟机安装的ubuntu20.0 ，然后本机浏览器安装宝塔并安装srs。在虚拟直播那里上传本机文件提示错误。
You got an error!
Request: http://192.168.161.100/terraform/v1/ffmpeg/vlive/upload/attach-file-0
Status: 500 Internal Server Error
Data: filename=2.mp4 mismatch attach-file-0

**Comment by winlinvip** [comment]
Can't reply.
