### ISSUE TITLE
The APIs and console control panel of SRS are all exposed to the public network, allowing others to arbitrarily kick the stream.

### ISSUE THREAD

**Issue by blblank** [ossrs/srs-cloud#59]
The APIs and console control panel of SRS are all exposed to the public network, allowing others to arbitrarily kick the stream. This issue also exists in SRS4, SRS5, and SRS6. I don't understand why there isn't a login authentication added.

**Comment by wuxianlijiang** [comment]
附议。

**Comment by winlinvip** [comment]
SRS API authentication, please refer to the SRS documentation, there are solutions.

This is the SRS Cloud project, which will disable the SRS HTTP API and Console.

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs-cloud/discussions/78?converting=1
